// RadioLoop Library Workspace (0717A) — POST /radio-package-retire.
// Node-only. Correction: retirement must never mutate an existing
// immutable package version. Whole-RadioLoop scope only for this build
// (per-version retirement is deferred — its governance semantics aren't
// specified). Clones the current highest version forward exactly like a
// metadata revision, but the new version's status is RETIRED and its
// arrangement/musical/approval are carried forward unchanged — retirement
// is a pure status transition, not a content edit.

import path from "node:path";
import { cloneVersionForward } from "./radioVersionCloneHelper";
import { finalizePackage, packageVersionDir } from "./radioPackageWriter";
import { releaseReservation } from "./radioIdAssigner";
import { readJsonSafe } from "./radioFsUtils";
import type { RadioLoopId, RadioLoopPackageManifest, RadioLoopSourceReference, RadioPackageVersion, RadioValidationIssue } from "../../src/data/radioLoopTypes";

export interface RetireRadioLoopRequest {
  radioLoopId: RadioLoopId;
  reason: string;
}

export interface RetireRadioLoopResult {
  ok: boolean;
  radioLoopId?: RadioLoopId;
  newPackageVersion?: RadioPackageVersion;
  assetHashMatch?: boolean;
  issues: RadioValidationIssue[];
}

export async function retireRadioLoop(radioLibraryRoot: string, operationId: string, request: RetireRadioLoopRequest): Promise<RetireRadioLoopResult> {
  if (!request.reason || !request.reason.trim()) {
    return { ok: false, issues: [{ code: "RADIO_RETIRE_REASON_REQUIRED", message: "A retirement reason is required", severity: "error" }] };
  }

  const clone = await cloneVersionForward(radioLibraryRoot, operationId, request.radioLoopId);
  if (!clone.ok) return { ok: false, issues: clone.issues };

  const sourceDir = packageVersionDir(radioLibraryRoot, request.radioLoopId, clone.sourcePackageVersion);
  const sourceReference = readJsonSafe<RadioLoopSourceReference>(path.join(sourceDir, "source-reference.json"));
  const retiredAt = new Date().toISOString();

  const metadata: RadioLoopPackageManifest = {
    ...clone.sourceMetadata,
    packageVersion: clone.newPackageVersion,
    status: "RETIRED",
    retirement: { reason: request.reason.trim(), retiredAt },
    // 0717C_MUSIC_Complete_Song_Intelligence_and_Section_Map §3.4 — a
    // retirement clone-forward is still a NEW package version; it never
    // perpetuates a legacy familyIds value either, even though everything
    // else in arrangement/musical/approval is otherwise carried forward
    // unchanged (retirement is a pure status transition, not a content
    // edit — but Compatibility Family is dead going forward regardless).
    arrangement: { ...clone.sourceMetadata.arrangement, familyIds: undefined },
  };

  const refreshedSourceReference: RadioLoopSourceReference = sourceReference
    ? { ...sourceReference, resolvedAt: retiredAt }
    : { trackId: metadata.source.trackId, loopId: metadata.source.loopId, startSeconds: 0, endSeconds: 0, resolvedAt: retiredAt };

  const finalizeResult = await finalizePackage({
    radioLibraryRoot,
    operationId,
    radioLoopId: request.radioLoopId,
    packageVersion: clone.newPackageVersion,
    metadata,
    sourceReference: refreshedSourceReference,
    reportBase: { startedAt: retiredAt, priorIssues: [] },
  });

  // Unlike a raw finalizePackage caller retrying the SAME operationId
  // (0716B's promotion flow), each call to this orchestrator is a
  // self-contained operation with its own fresh operationId (generated by
  // the route handler, exactly like /radio-staging-create already does) —
  // there is no legitimate reason to keep a reservation alive past a
  // failed attempt here, and doing so would otherwise skip a version
  // number on every subsequent real retry.
  if (!finalizeResult.ok) await releaseReservation(radioLibraryRoot, operationId);

  return {
    ok: finalizeResult.ok,
    radioLoopId: request.radioLoopId,
    newPackageVersion: clone.newPackageVersion,
    assetHashMatch: clone.assetHashMatch,
    issues: finalizeResult.report.issues,
  };
}
