// ── MapsGeographicStyleRegistry v1.0.0 ────────────────────────────────────────
// 0729A_MAPS_Palette_Audit_Default_Wiring; renamed from MapsPaletteRegistry by
// 0729D_MAPS_Vehicle_Overlay_Libraries_Foundation's terminology-migration gate.
// Status: active | Classification: presentation-authority / geographic-style-registry
//
// Builds the Phase 1 property registry for the MAPS Geographic Style system.
//
// Scope (Phase 1 — narrow, per 0729A build direction):
//   WIRED   — hosted Mapbox base-map layers (discovered live via map.getStyle(),
//             excluding building/fill-extrusion layers, which stay with the
//             existing per-building authoring authority), and the route
//             line/marker colors in mapboxOperatorRenderer/routePlannerRuntime/
//             routePanel.
//   DEFERRED / VESTIGIAL — everything else this audit found (actors, vessels,
//             aircraft, traffic, orbital-mode-only rendering, broader atmosphere,
//             sky shader, general application UI, per-building overrides, the
//             legacy MapStyleAuthority). Reported for completeness, not wired —
//             no setter APIs were added to those modules in this build.
//
// 0729_MAPS_Visual_Property_Authority_Audit additions — new WIRED properties:
//   line-opacity/fill-opacity on the hosted style's pattern-bearing and
//   soft-line layers (bridge/tunnel/road "-navigation" — see
//   _discoverPatternOpacity; the pattern sprite itself is baked into the
//   remote Mapbox Studio style, not addImage()'d locally, so pattern CHOICE
//   stays out of scope, opacity doesn't). Everything else this audit found
//   (OverlayRuntime's transit/isolation canvas layers, building illustration/
//   material/surface-texture patterns, the dormant harbor-geometry debug
//   renderer, and hardcoded cyan/teal literals outside this registry) is
//   cataloged honestly in getDeferredAudit() below, not wired — see the
//   audit report for the full inventory and why.
//
// vehicle.hero.* / hud.environmental.* / overlay.atmosphere-composite.enabled
// all moved OUT of this registry in 0729D Phase 2/3 — they are now discovered
// by the standalone vehicleStyleRegistry.js (Vehicles library) and
// overlayStyleRegistry.js (Overlays library), per the spec's "do not force
// vehicle materials or HUD/overlay effects into Geographic Styles."
//
// A raw property record is NOT tied to Mapbox specifically — see
// GeographicStylePropertySource below — but the base-map group is generated by
// walking the live style (map.getStyle()) rather than a hand-typed layer list,
// per the "runtime discovery over hand-authored records" build direction.
//
// Placement: wall/systems/presentation/mapsGeographicStyleRegistry.js
// Load: AFTER mapboxViewportRuntime.js, heroVehicleRenderer.js,
//       routePlannerRuntime.js, routePanel.js, mapboxOperatorRenderer.js,
//       environmentalTelemetryHUD.js. BEFORE mapsGeographicStyleAuthority.js.
// ──────────────────────────────────────────────────────────────────────────────
(function (global) {
  'use strict';

  var SBE     = (global.SBE = global.SBE || {});
  var VERSION = '1.0.0';

  /**
   * @typedef {"mapbox-style"|"route"|"vehicle"|"hud"|"overlay"} GeographicStylePropertySource
   *
   * @typedef {Object} GeographicStylePropertyRecord
   * @property {string} id                stable, deterministic id
   * @property {string} label             human-readable label
   * @property {string} group             UI group name
   * @property {GeographicStylePropertySource} source
   * @property {string} sourceLocation    file/module the property lives in
   * @property {string} [sourceObject]    layer id / object key, if applicable
   * @property {string} sourceProperty    property name within sourceObject
   * @property {*} currentValue           current value at audit/apply time
   * @property {"solid"|"expression"|"derived"|"opacity"|"boolean"} valueKind
   * @property {string|null} displayColor a representative solid hex/rgba for swatch display
   * @property {boolean} editable
   * @property {boolean} transitionable   can be live-applied without reload
   * @property {"wired"|"deferred"|"vestigial"} status
   * @property {string} ownerModule
   * @property {string} [notes]
   */

  // ── Color-bearing paint properties per Mapbox layer type ──────────────────
  var COLOR_PAINT_PROPS = {
    'fill':       ['fill-color', 'fill-outline-color'],
    'line':       ['line-color'],
    'circle':     ['circle-color', 'circle-stroke-color'],
    'symbol':     ['text-color', 'text-halo-color', 'icon-color'],
    'background': ['background-color'],
  };
  // fill-extrusion intentionally excluded — see _isBuildingLayer / deferred audit.

  function _isBuildingLayer(layer) {
    if (layer.type === 'fill-extrusion') return true;
    if (/building/i.test(layer.id || '')) return true;
    if (/building/i.test(layer['source-layer'] || '')) return true;
    return false;
  }

  function _classifyGroup(layer) {
    var probe = ((layer.id || '') + ' ' + (layer['source-layer'] || '')).toLowerCase();
    if (layer.type === 'background') return 'Base Map';
    if (/water|ocean|sea|lake|river|waterway/.test(probe)) return 'Water';
    if (/road|street|bridge|tunnel|highway|motorway|path/.test(probe)) return 'Roads';
    if (/label|place|poi|text|symbol/.test(probe)) return 'Labels';
    if (/boundary|border|admin/.test(probe)) return 'Boundaries';
    if (/land|landuse|landcover|park|golf|hospital|school|pitch|grass|wood/.test(probe)) return 'Land';
    return 'Base Map';
  }

  function _titleCase(s) {
    return s.replace(/[-_]/g, ' ').replace(/\b\w/g, function (c) { return c.toUpperCase(); }).trim();
  }

  function _readableLabel(layer, prop) {
    var propName = prop
      .replace(/^(fill-extrusion-|fill-|line-|circle-|text-|icon-|background-)/, '')
      .replace(/-/g, ' ');
    return _titleCase(layer.id) + ' — ' + _titleCase(propName);
  }

  function _representativeColor(value) {
    if (typeof value === 'string') {
      return /^#|^rgba?\(|^hsla?\(/i.test(value) ? value : null;
    }
    if (Array.isArray(value)) {
      var found = null;
      for (var i = 0; i < value.length; i++) {
        var v = value[i];
        if (typeof v === 'string' && /^#|^rgba?\(|^hsla?\(/i.test(v)) found = v;
        else if (Array.isArray(v)) {
          var nested = _representativeColor(v);
          if (nested) found = nested;
        }
      }
      return found;
    }
    return null;
  }

  function _valueKind(value) {
    if (typeof value === 'string') return 'solid';
    if (Array.isArray(value)) return 'expression';
    return 'derived';
  }

  // ── Base map — runtime discovery via map.getStyle() ───────────────────────
  // No hand-typed layer list. Naturally covers both style-authored layers and
  // any layer added/mutated at runtime, since getStyle() reflects live state.
  function _discoverBaseMap(map) {
    var records = [];
    if (!map || typeof map.getStyle !== 'function') return records;
    var style;
    try { style = map.getStyle(); } catch (e) { return records; }
    var layers = (style && style.layers) || [];
    layers.forEach(function (layer) {
      if (_isBuildingLayer(layer)) return;
      var props = COLOR_PAINT_PROPS[layer.type];
      if (!props) return;
      var paint = layer.paint || {};
      props.forEach(function (prop) {
        if (!(prop in paint)) return;
        var value = paint[prop];
        records.push({
          id:             'mapbox.' + layer.id + '.' + prop,
          label:          _readableLabel(layer, prop),
          group:          _classifyGroup(layer),
          source:         'mapbox-style',
          sourceLocation: 'hosted Mapbox Studio style — discovered live via map.getStyle()',
          sourceObject:   layer.id,
          sourceProperty: prop,
          currentValue:   value,
          valueKind:      _valueKind(value),
          displayColor:   _representativeColor(value),
          editable:       true,
          transitionable: true,
          status:         'wired',
          ownerModule:    'mapbox-style:' + layer.id,
        });
      });
    });
    return records;
  }

  // ── Route — mapboxOperatorRenderer.js / routePlannerRuntime.js / routePanel.js ──
  function _discoverRoute() {
    var mor = SBE.MapboxOperatorRenderer;
    var rpr = SBE.RoutePlannerRuntime;
    var rp  = SBE.RoutePanel;
    var colors = (mor && typeof mor.getColors === 'function') ? mor.getColors() : null;
    var defaultColor = (rpr && typeof rpr.getDefaultColor === 'function') ? rpr.getDefaultColor() : '#4a9eff';
    var indicatorColor = (rp && typeof rp.getVisibleColor === 'function') ? rp.getVisibleColor() : '#3dd8c5';

    return [
      {
        id: 'route.line.default-color', label: 'Route Line',
        group: 'Route', source: 'route',
        sourceLocation: 'wall/runtimes/routePlannerRuntime.js + wall/render/mapboxOperatorRenderer.js',
        sourceObject: 'RoutePlannerRuntime/MapboxOperatorRenderer', sourceProperty: 'routeLine',
        currentValue: (colors && colors.routeLine) || defaultColor,
        valueKind: 'solid', displayColor: (colors && colors.routeLine) || defaultColor,
        editable: true, transitionable: true, status: 'wired',
        ownerModule: 'routePlannerRuntime.js + mapboxOperatorRenderer.js',
      },
      {
        id: 'route.selection.color', label: 'Route Selection / Handles',
        group: 'Route', source: 'route',
        sourceLocation: 'wall/render/mapboxOperatorRenderer.js',
        sourceObject: 'MapboxOperatorRenderer', sourceProperty: 'selection',
        currentValue: (colors && colors.selection) || '#ffffff',
        valueKind: 'solid', displayColor: (colors && colors.selection) || '#ffffff',
        editable: true, transitionable: true, status: 'wired',
        ownerModule: 'mapboxOperatorRenderer.js',
      },
      {
        id: 'route.panel.visible-indicator', label: 'Route Panel Visibility Dot',
        group: 'Route', source: 'route',
        sourceLocation: 'wall/render/routePanel.js',
        sourceObject: 'RoutePanel', sourceProperty: 'visibleIndicator',
        currentValue: indicatorColor,
        valueKind: 'solid', displayColor: indicatorColor,
        editable: true, transitionable: true, status: 'wired',
        ownerModule: 'routePanel.js',
      },
    ];
  }

  // ── Opacity — hosted style, pattern/soft-line layers ──────────────────────
  // 0729_MAPS_Visual_Property_Authority_Audit — the bridge/tunnel/road
  // "-navigation" layers carry line-pattern (a sprite baked into the hosted
  // Mapbox Studio style — see wall/runtimes/broadcastStyleCleanup.js's own
  // audit()/apply(), which this discovery deliberately mirrors) and several
  // tunnel "-case" layers carry a soft line-opacity. Pattern CHOICE isn't
  // wired (swapping sprite images baked into the remote style is out of
  // scope — see the audit report), but opacity is a genuine, independently
  // controllable paint property on the same layers, discovered the same
  // live-from-map.getStyle() way as color.
  var OPACITY_PAINT_PROPS = {
    'fill':   ['fill-opacity'],
    'line':   ['line-opacity'],
    'circle': ['circle-opacity'],
  };

  function _hasPattern(paint) {
    return 'line-pattern' in paint || 'fill-pattern' in paint;
  }

  function _discoverPatternOpacity(map) {
    var records = [];
    if (!map || typeof map.getStyle !== 'function') return records;
    var style;
    try { style = map.getStyle(); } catch (e) { return records; }
    var layers = (style && style.layers) || [];
    layers.forEach(function (layer) {
      if (_isBuildingLayer(layer)) return;
      var paint = layer.paint || {};
      // Scope: only layers that actually carry a pattern or a soft (<1)
      // opacity — not every fill/line layer's opacity, to avoid ballooning
      // the schema with properties that were never flagged as part of this
      // audit's "pattern/soft-line" trace target.
      var opacityProp = (OPACITY_PAINT_PROPS[layer.type] || [])[0];
      if (!opacityProp || !(opacityProp in paint)) return;
      var opacityValue = paint[opacityProp];
      if (typeof opacityValue !== 'number') return; // expression-driven opacity — not a flat editable number
      if (!_hasPattern(paint) && opacityValue >= 1) return; // fully-opaque, no-pattern layers are out of this audit's scope
      records.push({
        id:             'mapbox-opacity.' + layer.id + '.' + opacityProp,
        label:          _readableLabel(layer, opacityProp),
        group:          _classifyGroup(layer),
        source:         'mapbox-style',
        sourceLocation: 'hosted Mapbox Studio style — discovered live via map.getStyle()',
        sourceObject:   layer.id,
        sourceProperty: opacityProp,
        currentValue:   String(opacityValue),
        valueKind:      'opacity',
        displayColor:   null,
        editable:       true,
        transitionable: true,
        status:         'wired',
        ownerModule:    'mapbox-style:' + layer.id,
        notes: _hasPattern(paint)
          ? 'Pattern-bearing layer (line-pattern/fill-pattern sprite baked into the hosted style) — pattern choice itself is not editable, opacity is.'
          : 'Soft-line layer (partial default opacity in the hosted style).',
      });
    });
    return records;
  }

  // ── Deferred / vestigial audit (Phase 1 — read-only, no setters added) ────
  // Counts are approximate where noted — these systems are intentionally not
  // re-enumerated exhaustively since they are not wired in this build.
  function getDeferredAudit() {
    return [
      {
        id: 'audit.actors.presentation-palette', label: 'Actor Presentation Palette (full migration)',
        group: 'Deferred — Actors', status: 'deferred',
        ownerModule: 'wall/systems/actors/actorPresentationPaletteRegistry.js',
        approxPropertyCount: 27,
        notes: 'Feeds ground-vehicle/actor mesh colors (worldSpaceVehicleLayer.js). Also the source ' +
               'the hero vehicle world-space mesh resolves through in normal (non-calibration) play — ' +
               'deferred per build direction, so the hero vehicle\'s steady-state rendered color is not ' +
               'wired; only its DOM/SVG fallback marker is (see the Vehicles library\'s Hero Car record, ' +
               'vehicleStyleRegistry.js, as of 0729D).',
      },
      {
        id: 'audit.marine.vessel-class-presentation', label: 'Vessel Class Presentation (live vessel colors)',
        group: 'Deferred — Vessels', status: 'deferred',
        ownerModule: 'wall/systems/presentation/vesselClassPresentation.js',
        approxPropertyCount: 11,
        notes: 'This is the registry marineRenderer.js actually renders from — deferred per build direction.',
      },
      {
        id: 'audit.marine.maritime-style-registry', label: 'Maritime Style Registry (vessel colors)',
        group: 'Vestigial — Vessels', status: 'vestigial',
        ownerModule: 'wall/systems/presentation/maritimeStyleRegistry.js',
        approxPropertyCount: 11,
        notes: 'Documented as the vessel color authority but not consumed by marineRenderer.js at ' +
               'runtime — VesselClassPresentation is used instead. Confirmed non-rendering via code audit.',
      },
      {
        id: 'audit.aircraft.object-profile-palettes', label: 'Aircraft Palettes + Trail/Light Literals',
        group: 'Deferred — Aircraft', status: 'deferred',
        ownerModule: 'wall/registries/objectProfileRegistry.js + wall/render/aircraftRenderer.js',
        approxPropertyCount: 10,
      },
      {
        id: 'audit.traffic.renderer-literals', label: 'Traffic Headlight/Taillight Gradient Literals',
        group: 'Deferred — Traffic', status: 'deferred',
        ownerModule: 'wall/render/trafficRenderer.js',
        approxPropertyCount: 6,
        notes: 'Inline literals, no existing indirection/registry to hook into.',
      },
      {
        id: 'audit.orbital.mode-controller', label: 'Orbital Mode Globe/Atmosphere Colors',
        group: 'Deferred — Orbital', status: 'deferred',
        ownerModule: 'wall/systems/orbital/OrbitalModeController.js',
        approxPropertyCount: 6,
        notes: 'Non-default "Earth from space" mode, not part of the standard map presentation.',
      },
      {
        id: 'audit.atmosphere.stage-lighting', label: 'Stage Lighting Phase Tints',
        group: 'Deferred — Atmosphere', status: 'deferred',
        ownerModule: 'wall/render/stageLightingRenderer.js',
        approxPropertyCount: 5,
        notes: 'PHASE_TINTS (dawn/day/dusk/night/lateNight) — the live-rendering table.',
      },
      {
        id: 'audit.atmosphere.city-rhythm', label: 'City Rhythm Phase Colors (debug-only duplicate)',
        group: 'Vestigial — Atmosphere', status: 'vestigial',
        ownerModule: 'wall/render/cityRhythmRenderer.js',
        approxPropertyCount: 5,
        notes: 'Separate _PHASE_COLORS table with different RGB values than stageLightingRenderer.js ' +
               'for the same phase names; gated behind a debug flag, not part of normal presentation.',
      },
      {
        id: 'audit.atmosphere.composite-cloud', label: 'Atmosphere Composite Internal Effect Colors / Cloud Base Tints',
        group: 'Deferred — Atmosphere', status: 'deferred',
        ownerModule: 'wall/render/atmosphereComposite.js + wall/render/cloudAtmosphereRenderer.js',
        approxPropertyCount: 8,
        notes: '0729_MAPS_Visual_Property_Authority_Audit wired the on/off toggle for this stack ' +
               '(see the Overlays library\'s Atmosphere Composite record, overlayStyleRegistry.js, as ' +
               'of 0729D) — its 7 internal effects ' +
               '(time-of-day tint, fog vignette, cloud-shadow sweep, rain tint, ambient veil, road-' +
               'reflectance strokes, mood-zone glow) still read from WorldAtmosphere/WorldLightingModel ' +
               'state with some hardcoded fallback tuples, not this palette, and remain deferred. ' +
               'cloudAtmosphereRenderer.js is confirmed dormant (init/render never called in the boot path).',
      },
      {
        id: 'audit.sky.three-sky-layer', label: 'Sky Shader Colors (zenith/horizon/sun/haze)',
        group: 'Deferred — Sky', status: 'deferred',
        ownerModule: 'wall/threeSkyLayer.js',
        approxPropertyCount: 6,
        notes: 'GLSL vec3 literals baked at shader-compile time — not live-transitionable without ' +
               'unmounting/recompiling the custom layer even if wired in a future build.',
      },
      {
        id: 'audit.ui.general-application-css', label: 'General Application UI Colors (wall/styles.css)',
        group: 'Deferred — Application UI', status: 'deferred',
        ownerModule: 'wall/styles.css',
        approxPropertyCount: 289,
        notes: '12 :root tokens + ~64 raw hex + ~225 rgba() literals beyond the route/HUD/hero chrome ' +
               'already wired above; a full literal-replacement sweep is out of scope for Phase 1.',
      },
      {
        id: 'audit.legacy.map-style-authority', label: 'Legacy MapStyleAuthority / MapStyleManifest',
        group: 'Vestigial — Legacy', status: 'vestigial',
        ownerModule: 'wall/systems/presentation/mapStyleAuthority.js',
        approxPropertyCount: null,
        notes: 'Well-documented "constitutional" authority, but not connected to any live Mapbox paint ' +
               'property or renderer — confirmed non-rendering via code audit.',
      },
      {
        id: 'audit.buildings.per-edit-overrides', label: 'Per-Building Author-Edit Overrides',
        group: 'Deferred — Buildings', status: 'deferred',
        ownerModule: 'wall/systems/presentation/buildingEditProjectionRuntime.js',
        approxPropertyCount: null,
        notes: 'Content-authoring feature (individually authored per-building colors), not a global ' +
               'theme property — a palette system overwriting it would destroy authored content. The ' +
               'base building fill-extrusion paint is likewise excluded from base-map discovery to avoid ' +
               'this authority and the palette system fighting over the same paint property.',
      },
      // ── 0729_MAPS_Visual_Property_Authority_Audit additions ─────────────────
      {
        id: 'audit.overlay.runtime-layers', label: 'OverlayRuntime — Transit Pulse / Isolation Fade canvas layers',
        group: 'Deferred — Overlays', status: 'deferred',
        ownerModule: 'wall/render/overlayRuntime.js + wall/render/overlays/transitPulseLayer.js + isolationFadeLayer.js',
        approxPropertyCount: 6,
        notes: 'init() runs at boot and registers both layers, but the runtime\'s master _enabled flag ' +
               'starts false and only flips true via a debug-only restore path — dormant on the canonical ' +
               'LIVE MAP by default (confirmed live: the "surface-overlay"/unlabeled OverlayRuntime canvas ' +
               'sampled 0 non-transparent pixels in the default view). transitPulseLayer.js hardcodes a ' +
               'cyan-blue gradient (rgba(120,200,255,…) / rgba(80,140,220,…)); isolationFadeLayer.js ' +
               'hardcodes greys — neither reads this palette. CinematicHazeLayer/SignalDriftLayer are ' +
               'registered in comments only (explicitly suspended: "haze flattens map readability; ' +
               'scanlines fight road typography").',
      },
      {
        id: 'audit.overlay.building-pattern-passes', label: 'Building Illustration / Material / Surface-Texture canvas patterns',
        group: 'Deferred — Overlays', status: 'deferred',
        ownerModule: 'wall/systems/presentation/buildingIllustrationPass.js + buildingMaterialIllustrationRuntime.js + allVisibleBuildingSurfaceTextureRuntime.js',
        approxPropertyCount: 3,
        notes: 'The only map.addImage()/fill-pattern generators in this codebase (canvas-drawn speckle/' +
               'grain/surface textures on building fills) — all three ship with _enabled=false and require ' +
               'an explicit wos.debug.*.enable() call; none run in the canonical default LIVE MAP.',
      },
      {
        id: 'audit.overlay.harbor-geometry-debug', label: 'Harbor Geometry Runtime Renderer (debug canvas)',
        group: 'Vestigial — Overlays', status: 'vestigial',
        ownerModule: 'wall/render/harborGeometryRuntimeRenderer.js + harborGeometryRuntimeStyle.js',
        approxPropertyCount: null,
        notes: 'init() is never called anywhere in the boot path — confirmed non-rendering via code audit. ' +
               'harborGeometryRuntimeStyle.js hardcodes real cyan values (rgba(55,200,245,…), ' +
               'rgba(40,215,255,…)); mapSurfaceRecovery.js:203-206 explicitly flags this file as a known ' +
               '"possible cyan grid" leak source if it is ever wired up.',
      },
      {
        id: 'audit.legacy.hardcoded-cyan-literals', label: 'Hardcoded cyan/teal literals outside the palette system',
        group: 'Deferred — Residual Color', status: 'deferred',
        ownerModule: 'wall/systems/world/surfaceStateManager.js:47, wall/systems/runtime/buildingReplacementRuntime.js:118, ' +
                     'wall/render/trafficFlowRenderer.js:16, wall/systems/transit/transitLiveryHooks.js:24, ' +
                     'wall/systems/transit/transitPresencePass.js:23, wall/systems/transit/cruiseMovementField.js:28, ' +
                     'wall/systems/actors/actorPresentationPaletteRegistry.js:30, wall/render/atmosphereComposite.js:295',
        approxPropertyCount: 8,
        notes: 'These are the genuine "would leak regardless of active Geographic Style" risks this audit ' +
               'found — each hardcodes its own cyan/teal (#3dd8c5 "teal (default)" / rgba(95,211,188,…) / ' +
               '#7dffe8 "cyan_infra" preset in transitPresencePass.js (cruiseMovementField.js\'s own same-named ' +
               'preset is a separate #6dffe8) / 0x20c7d8 "citibike.cyan" three.js hex / rr=120,rg=160,rb=220 ' +
               'road-reflectance) with no read from mapsGeographicStyleRegistry.js. NOT the same thing as the ' +
               'base map\'s own cyan-on-dark look, which is the hosted style\'s deliberate wos.dark.cyan ' +
               'default profile (wosMapStyleAuthority.js) and is correctly wired/editable via this registry ' +
               'already. mapSurfaceRecovery.js/presentationAuthorityAudit.js already run a live cyan-leak ' +
               'detector that protects known-intentional layers (land/water/road/bridge/tunnel/building/park) ' +
               'and flags the rest — these literals sit in renderers that are either dormant by default ' +
               '(harbor geometry, transit pulse) or apply to systems out of this build\'s scope (transit ' +
               'livery presets, actor palettes).',
      },
    ];
  }

  // ── Public API ─────────────────────────────────────────────────────────────
  function buildRegistry(map) {
    return [].concat(
      _discoverBaseMap(map),
      _discoverPatternOpacity(map),
      _discoverRoute()
    );
  }

  SBE.MapsGeographicStyleRegistry = Object.freeze({
    VERSION: VERSION,
    buildRegistry: buildRegistry,
    getDeferredAudit: getDeferredAudit,
  });

  // Temporary compat alias (0729D terminology migration) — remove once
  // nothing references the old name. New code must use MapsGeographicStyleRegistry.
  SBE.MapsPaletteRegistry = SBE.MapsGeographicStyleRegistry;

  console.log('[MapsGeographicStyleRegistry] v' + VERSION + ' loaded');

})(window);
