// ── MapsPaletteRegistry v1.0.0 ────────────────────────────────────────────────
// 0729A_MAPS_Palette_Audit_Default_Wiring
// Status: active | Classification: presentation-authority / palette-registry
//
// Builds the Phase 1 property registry for the MAPS palette system.
//
// Scope (Phase 1 — narrow, per 0729A build direction):
//   WIRED   — hosted Mapbox base-map layers (discovered live via map.getStyle(),
//             excluding building/fill-extrusion layers, which stay with the
//             existing per-building authoring authority), the route line/marker
//             colors in mapboxOperatorRenderer/routePlannerRuntime/routePanel,
//             the hero vehicle DOM/SVG marker colors, and the default
//             environmental HUD colors.
//   DEFERRED / VESTIGIAL — everything else this audit found (actors, vessels,
//             aircraft, traffic, orbital-mode-only rendering, broader atmosphere,
//             sky shader, general application UI, per-building overrides, the
//             legacy MapStyleAuthority). Reported for completeness, not wired —
//             no setter APIs were added to those modules in this build.
//
// A raw property record is NOT tied to Mapbox specifically — see
// PalettePropertySource below — but the base-map group is generated by walking
// the live style (map.getStyle()) rather than a hand-typed layer list, per the
// "runtime discovery over hand-authored records" build direction.
//
// Placement: wall/systems/presentation/mapsPaletteRegistry.js
// Load: AFTER mapboxViewportRuntime.js, heroVehicleRenderer.js,
//       routePlannerRuntime.js, routePanel.js, mapboxOperatorRenderer.js,
//       environmentalTelemetryHUD.js. BEFORE mapsPaletteAuthority.js.
// ──────────────────────────────────────────────────────────────────────────────
(function (global) {
  'use strict';

  var SBE     = (global.SBE = global.SBE || {});
  var VERSION = '1.0.0';

  /**
   * @typedef {"mapbox-style"|"route"|"vehicle"|"hud"} PalettePropertySource
   *
   * @typedef {Object} PalettePropertyRecord
   * @property {string} id                stable, deterministic id
   * @property {string} label             human-readable label
   * @property {string} group             UI group name
   * @property {PalettePropertySource} source
   * @property {string} sourceLocation    file/module the property lives in
   * @property {string} [sourceObject]    layer id / object key, if applicable
   * @property {string} sourceProperty    property name within sourceObject
   * @property {*} currentValue           current value at audit/apply time
   * @property {"solid"|"expression"|"derived"} valueKind
   * @property {string|null} displayColor a representative solid hex/rgba for swatch display
   * @property {boolean} editable
   * @property {boolean} transitionable   can be live-applied without reload
   * @property {"wired"|"deferred"|"vestigial"} status
   * @property {string} ownerModule
   * @property {string} [notes]
   */

  // ── Color-bearing paint properties per Mapbox layer type ──────────────────
  var COLOR_PAINT_PROPS = {
    'fill':       ['fill-color', 'fill-outline-color'],
    'line':       ['line-color'],
    'circle':     ['circle-color', 'circle-stroke-color'],
    'symbol':     ['text-color', 'text-halo-color', 'icon-color'],
    'background': ['background-color'],
  };
  // fill-extrusion intentionally excluded — see _isBuildingLayer / deferred audit.

  function _isBuildingLayer(layer) {
    if (layer.type === 'fill-extrusion') return true;
    if (/building/i.test(layer.id || '')) return true;
    if (/building/i.test(layer['source-layer'] || '')) return true;
    return false;
  }

  function _classifyGroup(layer) {
    var probe = ((layer.id || '') + ' ' + (layer['source-layer'] || '')).toLowerCase();
    if (layer.type === 'background') return 'Base Map';
    if (/water|ocean|sea|lake|river|waterway/.test(probe)) return 'Water';
    if (/road|street|bridge|tunnel|highway|motorway|path/.test(probe)) return 'Roads';
    if (/label|place|poi|text|symbol/.test(probe)) return 'Labels';
    if (/boundary|border|admin/.test(probe)) return 'Boundaries';
    if (/land|landuse|landcover|park|golf|hospital|school|pitch|grass|wood/.test(probe)) return 'Land';
    return 'Base Map';
  }

  function _titleCase(s) {
    return s.replace(/[-_]/g, ' ').replace(/\b\w/g, function (c) { return c.toUpperCase(); }).trim();
  }

  function _readableLabel(layer, prop) {
    var propName = prop
      .replace(/^(fill-extrusion-|fill-|line-|circle-|text-|icon-|background-)/, '')
      .replace(/-/g, ' ');
    return _titleCase(layer.id) + ' — ' + _titleCase(propName);
  }

  function _representativeColor(value) {
    if (typeof value === 'string') {
      return /^#|^rgba?\(|^hsla?\(/i.test(value) ? value : null;
    }
    if (Array.isArray(value)) {
      var found = null;
      for (var i = 0; i < value.length; i++) {
        var v = value[i];
        if (typeof v === 'string' && /^#|^rgba?\(|^hsla?\(/i.test(v)) found = v;
        else if (Array.isArray(v)) {
          var nested = _representativeColor(v);
          if (nested) found = nested;
        }
      }
      return found;
    }
    return null;
  }

  function _valueKind(value) {
    if (typeof value === 'string') return 'solid';
    if (Array.isArray(value)) return 'expression';
    return 'derived';
  }

  // ── Base map — runtime discovery via map.getStyle() ───────────────────────
  // No hand-typed layer list. Naturally covers both style-authored layers and
  // any layer added/mutated at runtime, since getStyle() reflects live state.
  function _discoverBaseMap(map) {
    var records = [];
    if (!map || typeof map.getStyle !== 'function') return records;
    var style;
    try { style = map.getStyle(); } catch (e) { return records; }
    var layers = (style && style.layers) || [];
    layers.forEach(function (layer) {
      if (_isBuildingLayer(layer)) return;
      var props = COLOR_PAINT_PROPS[layer.type];
      if (!props) return;
      var paint = layer.paint || {};
      props.forEach(function (prop) {
        if (!(prop in paint)) return;
        var value = paint[prop];
        records.push({
          id:             'mapbox.' + layer.id + '.' + prop,
          label:          _readableLabel(layer, prop),
          group:          _classifyGroup(layer),
          source:         'mapbox-style',
          sourceLocation: 'hosted Mapbox Studio style — discovered live via map.getStyle()',
          sourceObject:   layer.id,
          sourceProperty: prop,
          currentValue:   value,
          valueKind:      _valueKind(value),
          displayColor:   _representativeColor(value),
          editable:       true,
          transitionable: true,
          status:         'wired',
          ownerModule:    'mapbox-style:' + layer.id,
        });
      });
    });
    return records;
  }

  // ── Route — mapboxOperatorRenderer.js / routePlannerRuntime.js / routePanel.js ──
  function _discoverRoute() {
    var mor = SBE.MapboxOperatorRenderer;
    var rpr = SBE.RoutePlannerRuntime;
    var rp  = SBE.RoutePanel;
    var colors = (mor && typeof mor.getColors === 'function') ? mor.getColors() : null;
    var defaultColor = (rpr && typeof rpr.getDefaultColor === 'function') ? rpr.getDefaultColor() : '#4a9eff';
    var indicatorColor = (rp && typeof rp.getVisibleColor === 'function') ? rp.getVisibleColor() : '#3dd8c5';

    return [
      {
        id: 'route.line.default-color', label: 'Route Line',
        group: 'Route', source: 'route',
        sourceLocation: 'wall/runtimes/routePlannerRuntime.js + wall/render/mapboxOperatorRenderer.js',
        sourceObject: 'RoutePlannerRuntime/MapboxOperatorRenderer', sourceProperty: 'routeLine',
        currentValue: (colors && colors.routeLine) || defaultColor,
        valueKind: 'solid', displayColor: (colors && colors.routeLine) || defaultColor,
        editable: true, transitionable: true, status: 'wired',
        ownerModule: 'routePlannerRuntime.js + mapboxOperatorRenderer.js',
      },
      {
        id: 'route.selection.color', label: 'Route Selection / Handles',
        group: 'Route', source: 'route',
        sourceLocation: 'wall/render/mapboxOperatorRenderer.js',
        sourceObject: 'MapboxOperatorRenderer', sourceProperty: 'selection',
        currentValue: (colors && colors.selection) || '#ffffff',
        valueKind: 'solid', displayColor: (colors && colors.selection) || '#ffffff',
        editable: true, transitionable: true, status: 'wired',
        ownerModule: 'mapboxOperatorRenderer.js',
      },
      {
        id: 'route.panel.visible-indicator', label: 'Route Panel Visibility Dot',
        group: 'Route', source: 'route',
        sourceLocation: 'wall/render/routePanel.js',
        sourceObject: 'RoutePanel', sourceProperty: 'visibleIndicator',
        currentValue: indicatorColor,
        valueKind: 'solid', displayColor: indicatorColor,
        editable: true, transitionable: true, status: 'wired',
        ownerModule: 'routePanel.js',
      },
    ];
  }

  // ── Hero vehicle — heroVehicleRenderer.js DOM/SVG marker ──────────────────
  function _discoverHeroVehicle() {
    var hvr = SBE.HeroVehicleRenderer;
    var colors = (hvr && typeof hvr.getColors === 'function') ? hvr.getColors() : null;
    var DEFAULTS = {
      body: '#c8352e', roof: '#a02820', windshield: '#c8e8ff',
      rearGlass: '#9ab8d0', chevron: '#ffd34d', headlight: '#fffbe0',
    };
    var LABELS = {
      body: 'Hero Vehicle Body', roof: 'Hero Vehicle Roof', windshield: 'Hero Vehicle Windshield',
      rearGlass: 'Hero Vehicle Rear Glass', chevron: 'Hero Vehicle Heading Chevron', headlight: 'Hero Vehicle Headlights',
    };
    return Object.keys(DEFAULTS).map(function (key) {
      var value = (colors && colors[key]) || DEFAULTS[key];
      return {
        id: 'vehicle.hero.' + key, label: LABELS[key],
        group: 'Vehicles', source: 'vehicle',
        sourceLocation: 'wall/systems/render/heroVehicleRenderer.js',
        sourceObject: 'HeroVehicleRenderer', sourceProperty: key,
        currentValue: value, valueKind: 'solid', displayColor: value,
        editable: true, transitionable: true, status: 'wired',
        ownerModule: 'heroVehicleRenderer.js',
        notes: 'DOM/SVG marker path — used at initial load, calibration modes (block/slab/wedge), ' +
               'and as fallback when WorldSpaceVehicleLayer is unavailable. The steady-state world-space ' +
               'vehicle mesh resolves its color via ActorPresentationPaletteRegistry (deferred; see audit).',
      };
    });
  }

  // ── HUD — environmentalTelemetryHUD.js ────────────────────────────────────
  function _discoverHud() {
    var hud = SBE.EnvironmentalTelemetryHUD;
    var colors = (hud && typeof hud.getColors === 'function') ? hud.getColors() : null;
    var DEFAULTS = {
      live: 'rgba(120,220,120,0.70)', stale: 'rgba(220,180,80,0.60)', offline: 'rgba(255,255,255,0.15)',
      text: 'rgba(255,255,255,0.45)',
    };
    var LABELS = {
      live: 'HUD Status — Live', stale: 'HUD Status — Stale', offline: 'HUD Status — Offline',
      text: 'HUD Reality Row Text',
    };
    return Object.keys(DEFAULTS).map(function (key) {
      var value = (colors && colors[key]) || DEFAULTS[key];
      return {
        id: 'hud.environmental.' + key, label: LABELS[key],
        group: 'HUD', source: 'hud',
        sourceLocation: 'wall/render/environmentalTelemetryHUD.js',
        sourceObject: 'EnvironmentalTelemetryHUD', sourceProperty: key,
        currentValue: value, valueKind: 'solid', displayColor: value,
        editable: true, transitionable: true, status: 'wired',
        ownerModule: 'environmentalTelemetryHUD.js',
      };
    });
  }

  // ── Deferred / vestigial audit (Phase 1 — read-only, no setters added) ────
  // Counts are approximate where noted — these systems are intentionally not
  // re-enumerated exhaustively since they are not wired in this build.
  function getDeferredAudit() {
    return [
      {
        id: 'audit.actors.presentation-palette', label: 'Actor Presentation Palette (full migration)',
        group: 'Deferred — Actors', status: 'deferred',
        ownerModule: 'wall/systems/actors/actorPresentationPaletteRegistry.js',
        approxPropertyCount: 27,
        notes: 'Feeds ground-vehicle/actor mesh colors (worldSpaceVehicleLayer.js). Also the source ' +
               'the hero vehicle world-space mesh resolves through in normal (non-calibration) play — ' +
               'deferred per build direction, so the hero vehicle\'s steady-state rendered color is not ' +
               'wired in Phase 1; only its DOM/SVG fallback marker is (see vehicle.hero.* records).',
      },
      {
        id: 'audit.marine.vessel-class-presentation', label: 'Vessel Class Presentation (live vessel colors)',
        group: 'Deferred — Vessels', status: 'deferred',
        ownerModule: 'wall/systems/presentation/vesselClassPresentation.js',
        approxPropertyCount: 11,
        notes: 'This is the registry marineRenderer.js actually renders from — deferred per build direction.',
      },
      {
        id: 'audit.marine.maritime-style-registry', label: 'Maritime Style Registry (vessel colors)',
        group: 'Vestigial — Vessels', status: 'vestigial',
        ownerModule: 'wall/systems/presentation/maritimeStyleRegistry.js',
        approxPropertyCount: 11,
        notes: 'Documented as the vessel color authority but not consumed by marineRenderer.js at ' +
               'runtime — VesselClassPresentation is used instead. Confirmed non-rendering via code audit.',
      },
      {
        id: 'audit.aircraft.object-profile-palettes', label: 'Aircraft Palettes + Trail/Light Literals',
        group: 'Deferred — Aircraft', status: 'deferred',
        ownerModule: 'wall/registries/objectProfileRegistry.js + wall/render/aircraftRenderer.js',
        approxPropertyCount: 10,
      },
      {
        id: 'audit.traffic.renderer-literals', label: 'Traffic Headlight/Taillight Gradient Literals',
        group: 'Deferred — Traffic', status: 'deferred',
        ownerModule: 'wall/render/trafficRenderer.js',
        approxPropertyCount: 6,
        notes: 'Inline literals, no existing indirection/registry to hook into.',
      },
      {
        id: 'audit.orbital.mode-controller', label: 'Orbital Mode Globe/Atmosphere Colors',
        group: 'Deferred — Orbital', status: 'deferred',
        ownerModule: 'wall/systems/orbital/OrbitalModeController.js',
        approxPropertyCount: 6,
        notes: 'Non-default "Earth from space" mode, not part of the standard map presentation.',
      },
      {
        id: 'audit.atmosphere.stage-lighting', label: 'Stage Lighting Phase Tints',
        group: 'Deferred — Atmosphere', status: 'deferred',
        ownerModule: 'wall/render/stageLightingRenderer.js',
        approxPropertyCount: 5,
        notes: 'PHASE_TINTS (dawn/day/dusk/night/lateNight) — the live-rendering table.',
      },
      {
        id: 'audit.atmosphere.city-rhythm', label: 'City Rhythm Phase Colors (debug-only duplicate)',
        group: 'Vestigial — Atmosphere', status: 'vestigial',
        ownerModule: 'wall/render/cityRhythmRenderer.js',
        approxPropertyCount: 5,
        notes: 'Separate _PHASE_COLORS table with different RGB values than stageLightingRenderer.js ' +
               'for the same phase names; gated behind a debug flag, not part of normal presentation.',
      },
      {
        id: 'audit.atmosphere.composite-cloud', label: 'Atmosphere Composite / Cloud Base Tints',
        group: 'Deferred — Atmosphere', status: 'deferred',
        ownerModule: 'wall/render/atmosphereComposite.js + wall/render/cloudAtmosphereRenderer.js',
        approxPropertyCount: 8,
        notes: 'Weather-driven computed gradients built from a small set of base RGB triples.',
      },
      {
        id: 'audit.sky.three-sky-layer', label: 'Sky Shader Colors (zenith/horizon/sun/haze)',
        group: 'Deferred — Sky', status: 'deferred',
        ownerModule: 'wall/threeSkyLayer.js',
        approxPropertyCount: 6,
        notes: 'GLSL vec3 literals baked at shader-compile time — not live-transitionable without ' +
               'unmounting/recompiling the custom layer even if wired in a future build.',
      },
      {
        id: 'audit.ui.general-application-css', label: 'General Application UI Colors (wall/styles.css)',
        group: 'Deferred — Application UI', status: 'deferred',
        ownerModule: 'wall/styles.css',
        approxPropertyCount: 289,
        notes: '12 :root tokens + ~64 raw hex + ~225 rgba() literals beyond the route/HUD/hero chrome ' +
               'already wired above; a full literal-replacement sweep is out of scope for Phase 1.',
      },
      {
        id: 'audit.legacy.map-style-authority', label: 'Legacy MapStyleAuthority / MapStyleManifest',
        group: 'Vestigial — Legacy', status: 'vestigial',
        ownerModule: 'wall/systems/presentation/mapStyleAuthority.js',
        approxPropertyCount: null,
        notes: 'Well-documented "constitutional" authority, but not connected to any live Mapbox paint ' +
               'property or renderer — confirmed non-rendering via code audit.',
      },
      {
        id: 'audit.buildings.per-edit-overrides', label: 'Per-Building Author-Edit Overrides',
        group: 'Deferred — Buildings', status: 'deferred',
        ownerModule: 'wall/systems/presentation/buildingEditProjectionRuntime.js',
        approxPropertyCount: null,
        notes: 'Content-authoring feature (individually authored per-building colors), not a global ' +
               'theme property — a palette system overwriting it would destroy authored content. The ' +
               'base building fill-extrusion paint is likewise excluded from base-map discovery to avoid ' +
               'this authority and the palette system fighting over the same paint property.',
      },
    ];
  }

  // ── Public API ─────────────────────────────────────────────────────────────
  function buildRegistry(map) {
    return [].concat(
      _discoverBaseMap(map),
      _discoverRoute(),
      _discoverHeroVehicle(),
      _discoverHud()
    );
  }

  SBE.MapsPaletteRegistry = Object.freeze({
    VERSION: VERSION,
    buildRegistry: buildRegistry,
    getDeferredAudit: getDeferredAudit,
  });

  console.log('[MapsPaletteRegistry] v' + VERSION + ' loaded');

})(window);
