// Machine Life Research Workspace — data layer (0811_MACHINE-LIFE_MUSIC-
// Research-Workspace-Handoff_v1.0.0). Typed entities for a bounded MUSIC
// integration with the Machine Life Stage 0 Pre-Life research collection.
//
// Machine Life Stage 0 is a deterministic procedural collage system, not a
// trained AI music model (see stage-00-pre-life-manifest.json's
// `identity_note`). Nothing in this module or its consumers may describe
// recordings as generated by a trained model.
//
// Two data families are kept structurally separate per the handoff spec:
//   - MachineLifeCollection / MachineLifeRecording — imported, IMMUTABLE
//     manifest data. A review edit must never mutate these fields.
//   - MachineLifeRecordingReview — editable review data, keyed by
//     recordingId, stored independently.
// Proxy metadata (MachineLifeProxyAudio) is separate from both — MP3
// listening proxies are audition-only and never substitute for canonical
// WAV identity, filename, provenance, or checksum.

export const MACHINE_LIFE_PRE_LIFE_MANIFEST_SCHEMA =
  "machine-life-stage-00-pre-life-manifest-v1" as const;

export type MachineLifeLifeScore = 0 | 1 | 2;

export type MachineLifeDisposition =
  | "preserve"
  | "extract"
  | "develop"
  | "resident-seed"
  | "system-clue"
  | "dormant";

export type MachineLifeCategory =
  | "signal"
  | "pulse"
  | "texture"
  | "environment"
  | "gesture"
  | "collision"
  | "structure"
  | "free-dream";

export type MachineLifeConstructionMode = "layer" | "sequence";

export type MachineLifeSourceCollection = "primitive" | "studiorich-raw" | "transformations";

// Direct source relationship exactly as recorded in the manifest/recipe —
// never expanded to full raw-source ancestry unless the transformation
// manifest/recipes required to prove that expansion are also loaded (see
// machineLifeSelectors.ts).
export interface MachineLifeSourceUse {
  filename: string;
  collection: MachineLifeSourceCollection;
  sha256: string;
  startSeconds: number;
}

// One immutable Pre-Life recording, exactly as imported from
// stage-00-pre-life-manifest.json. Never mutated by a review edit.
export interface MachineLifeRecording {
  id: string; // e.g. "ml-prelife-0001" — stable, unique within a collection
  category: MachineLifeCategory;
  mode: MachineLifeConstructionMode;
  seed: number;
  durationSeconds: number;
  canonicalFilename: string; // the .wav filename named by the manifest
  canonicalChecksumSha256: string;
  sourceUses: MachineLifeSourceUse[];
  waveformEvidencePath?: string;
  spectrogramEvidencePath?: string;
  recipeEvidencePath?: string;
}

// One raw StudioRich source recording referenced by the collection's
// source_inventory (collection === "studiorich-raw"). Kept separate from
// MachineLifeRecording because raw sources are inputs, not Pre-Life outputs.
export interface MachineLifeRawSource {
  filename: string;
  checksumSha256: string;
  durationSeconds?: number;
}

// Immutable, imported manifest data for one Machine Life collection. A
// "duplicate collection/version import" is detected by (id, version)
// equality — see machineLifeManifestAdapter.ts.
export interface MachineLifeCollection {
  id: string; // deterministic from schema+engine+recordingCount+recording ids
  schema: typeof MACHINE_LIFE_PRE_LIFE_MANIFEST_SCHEMA;
  collectionVersion: string; // "Stage-00-Pre-Life-Recordings-v1" style label, from source_collections
  engine: string;
  engineVersion: string;
  identityNote: string; // manifest's own deterministic/non-model statement, preserved verbatim
  recordingCount: number;
  recordings: MachineLifeRecording[];
  rawSources: MachineLifeRawSource[];
  importedAt: string;
  importSourceManifestPath: string; // WOS Share relative path the manifest was read from, for provenance display only — never used as a runtime playback path
}

export type MachineLifeReplay = boolean;

// Editable review data. Storage key is recordingId. Never contains or
// mutates any MachineLifeRecording field.
export interface MachineLifeRecordingReview {
  recordingId: string;
  firstImage: string;
  strongestMomentStartSeconds: number | null;
  strongestMomentEndSeconds: number | null;
  lifeScore: MachineLifeLifeScore | null;
  replay: MachineLifeReplay | null;
  immediateNote: string;
  usefulSourceRelationship: string;
  behaviorDiscovered: string;
  disposition: MachineLifeDisposition | null;
  nextAction: string;
  reviewedAt: string | null;
}

export function createEmptyMachineLifeReview(recordingId: string): MachineLifeRecordingReview {
  return {
    recordingId,
    firstImage: "",
    strongestMomentStartSeconds: null,
    strongestMomentEndSeconds: null,
    lifeScore: null,
    replay: null,
    immediateNote: "",
    usefulSourceRelationship: "",
    behaviorDiscovered: "",
    disposition: null,
    nextAction: "",
    reviewedAt: null,
  };
}

// Review completion is a derived read (see machineLifeSelectors.ts,
// reviewCompleteness) — not stored — so a review can be saved with only
// some fields set (§ Review rules: "may be saved without every field, but
// completion status must remain incomplete").
export type MachineLifeReviewCompleteness = "unreviewed" | "partial" | "complete";

export type MachineLifeProxyKind = "pre-life" | "raw";

// Proxy metadata, kept separate from canonical MachineLifeRecording /
// MachineLifeRawSource data. audioRelPath is the same portable,
// LIBRARY_ROOT-relative path convention used by Track.audioRelPath —
// resolved for playback via /music-audio/${audioRelPath}, exactly like any
// other imported track. Never an absolute filesystem path.
export interface MachineLifeProxyAudio {
  kind: MachineLifeProxyKind;
  stem: string; // filename stem, e.g. "ml-prelife-0001-signal-seed-8001"
  proxyFileName: string; // e.g. "ml-prelife-0001-signal-seed-8001.mp3"
  audioRelPath: string; // portable, e.g. "machine-life/pre-life/ml-prelife-0001-signal-seed-8001.mp3"
  importedAt: string;
  durationSeconds: number | null; // decoded client-side at import time; never assumed equal to canonical duration
}

export interface MachineLifeProxyImportIssue {
  kind: MachineLifeProxyKind;
  stem: string;
  reason: "missing" | "duplicate" | "undecodable" | "upload_failed";
  detail?: string;
}

// One committed Machine Life "project" slice: a collection plus whatever
// proxies have been associated with it so far. Proxies may lag the
// collection import (§ "must not fabricate availability for missing local
// WAVs" / MP3 proxies) — audio availability is always computed from what is
// actually present, never assumed.
export interface MachineLifeProxyLibrary {
  collectionId: string;
  proxies: MachineLifeProxyAudio[];
  issues: MachineLifeProxyImportIssue[];
}
